title: Self Evidence
description: Self Evidence is a platform for cleaning and analyzing publicly available data.
baseurl: "" # for user.github.io root, leave empty
url: "https://selfevidence.github.io" # your GitHub Pages URL

# GitHub Pages will use these defaults
theme: minima

# Set this if you're using the docs folder
source: docs

# Optional: exclude things from being processed
exclude:
  - README.md
  # - Gemfile
  # - Gemfile.lock